version: '3.8'

services:
  # React Frontend
  frontend:
    build: ./frontend  # Path to your React app
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3000

  # Node.js Backend
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=myproject  # Changed to match your DB name
      - PGPASSWORD=Abiraj007
      - PGPORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis

  # PostgreSQL database - REMOVED THE EXTRA "services:" LINE
  db:
    image: postgres:13-alpine
    volumes:
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=myproject   # ← This automatically creates the database!
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Abiraj007
    ports:
      - "5432:5432"

  # Redis for Bull queue
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: